export { createClient } from './client'
export { createSupabaseServerClient } from './server'
export { createSupabaseServerClient as getServerClient } from './server'
export type { SupabaseClient } from '@supabase/supabase-js'
export type { User, Inquiry, Response, AnalyticsEvent, InquiryStatus, ResponseStatus, InquirySource, EventType, Feedback, FeedbackCategory, FeedbackStatus, Subscriber, SubscriptionStatus, DigestLog } from './database.types'